### ISSUE TITLE
Onyx error while auto generating easy, medium and hard on my expert chart

### ISSUE THREAD

**Issue by Joshwantsmaccas** [mtolly/onyxite-customs#150] opened 2020-04-29 04:11 UTC
so i got an error while using Onyx to auto generate easy, medium and hard on my expert chart. Never had this happen before and ive done a fair few using this method. This has stumped me as i dont seem to have done anything differently to all the others

Link to error - https://imgur.com/8pApGrF

Link to chart - https://drive.google.com/open?id=1XcVnRo3nldp63ssfqd2EY9IZPXbdyUjU

**Comment by mtolly** [comment] 2020-04-29 16:40
Hey there, turns out the issue is that my code did not handle the 4-note chords in the intro correctly -- it was supposed to reduce them to 2 notes on Hard but did not, so then later in the process when it tries to make fret jumps smaller, it wasn't expecting any chords with green and orange together :) I'll get a fixed build up soon, but here is a midi output by a version with the fix applied.

[reduced.mid.zip](https://github.com/mtolly/onyxite-customs/files/4553026/reduced.mid.zip)

Also by the way, I noticed while testing that my CH/PS import process doesn't fully detect the "guitar coop" part - it looks like it did the reduction on it okay, but I'll make sure that is also fixed in the next version.

**Comment by Joshwantsmaccas** [comment] 2020-04-30 09:49
thankyou so much! i also wanted to say that when trying to use the new preview feature, i get no video, just the audio, I'm gonna assume this is a phase shift issue since i also cant even get into the menus of due to (from what google has shown me) my new GPU (5700xt, I've seen a few people with the new 5000 series amd cards having the same issues) just thought id let you now of this aswell :)

**Comment by mtolly** [comment] 2020-05-14 02:49
New build is up that fixes this crash, and also should fix the 3D preview on your AMD card - there was an issue that probably affected all AMD/ATI cards on Windows due to a difference in OpenGL behavior on their drivers, so let me know if that still doesn't work for you.

**Closed by mtolly** 2020-05-14 02:49 UTC
