### ISSUE TITLE
Onyx Unresponsive

### ISSUE THREAD

**Issue by foodgod12** [mtolly/onyxite-customs#189] opened 2022-01-16 05:23 UTC
I use Onyx on Mac, and it has been running smoothly up until recently. Now, when I try to upload an RB3 file in order to convert it to a CH/PS file, once I click save after choosing the destination for the new file, the app becomes unresponsive and completely freezes, which doesn't allow me to convert the songs. I did recently update the OS on my Mac to Monterey and I think that may be the reason why, but I am coming here to make sure that is the case and see if there's a fix to this problem.

**Comment by mtolly** [comment] 2022-02-21 03:48
Yeah, this sounds like potentially an issue interacting with permissions changes in Monterey; someone else mentioned a similar problem in #177 (though not having the app freeze). Unfortunately I don't have a Mac at the moment to test on, so I'm not sure when I'll be able to track it down, but I'll see if I can either borrow a machine or set up a virtual machine.

**Comment by mtolly** [comment] 2022-03-20 17:43
This should now be fixed in the build I just put up of `20220319`. Let me know if that does not solve your issue.

**Closed by mtolly** 2022-03-20 17:43 UTC

**Comment by foodgod12** [comment] 2022-03-20 18:05
After I downloaded the new version and tried to open it, it now tells me "'Onyx' is damaged and can’t be opened. You should move it to the Trash." I'm not sure if it's a problem with my computer or the app itself. Thanks for getting back to me also.

**Comment by mtolly** [comment] 2022-03-20 19:00
Ah, that is due to it being an "unsigned" app (something I would have to pay Apple to fix...). One of these steps should hopefully work-

1. According to https://support.apple.com/en-in/guide/mac-help/mh40616/mac you may just be able to right-click the .app and select "Open", then confirm in the popup that comes up.
2. If that doesn't work, you may need to run a Terminal command from https://apple.stackexchange.com/questions/372084/macos-catalina-app-is-damaged-and-cant-be-opened-you-should-move-it-to-the-t , something like: `sudo xattr -rd com.apple.quarantine /Applications/Onyx.app`

**Comment by aure** [comment] 2022-03-20 19:03
I can confirm the second step works.

**Comment by foodgod12** [comment] 2022-03-20 23:53
It may be my computer then, neither of those steps work. The problem persists when I try the first suggestion and when I try to do the Terminal command nothing happens once I enter my password. Thank you for the help regardless.

**Comment by foodgod12** [comment] 2022-03-20 23:56
All good now, I appreciate the help
